name: Upload to Maven Central

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Upload archives
      run: ./gradlew uploadArchives
      env:
        GPG_KEY_ID: ${{secrets.GPG_KEY_ID}}
        GPG_KEY_LOCATION: ${{secrets.GPG_KEY_LOCATION}}
        GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
        OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
        OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
